# The Basics of NumPy Arrays

In [78]:
distances = [10, 15, 17, 26]
times = [0.3, 0.47, 0.55, 1.20]

In [79]:
velocity = []
for d,t in zip(distances, times):
    velocity.append(d/t)    

velocity

[33.333333333333336,
 31.914893617021278,
 30.909090909090907,
 21.666666666666668]

In [83]:
import numpy as np

In [86]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=10)  # 1D array
x2 = np.random.randint(10, size=(3, 4))  # 2D array
x3 = np.random.randint(10, size=(3, 4, 5))  # 3D array

In [3]:
print "x3 ndim: ", x3.ndim
print "x3 shape:", x3.shape 
print "x3 size: ", x3.size

x3 ndim:  3
x3 shape: (3L, 4L, 5L)
x3 size:  60


In [87]:
print "dtype:", x3.dtype

dtype: int32


In [88]:
print "itemsize:", x3.itemsize, "bytes"
print "nbytes:", x3.nbytes, "bytes"

itemsize: 4 bytes
nbytes: 240 bytes


In [89]:
x1

array([5, 0, 3, 3, 7, 9, 3, 5, 2, 4])

In [91]:
x1[1]

0

In [92]:
x1[4]

7

In [93]:
x1[-1]

4

In [94]:
x1[-2]

2

In [95]:
x2

array([[7, 6, 8, 8],
       [1, 6, 7, 7],
       [8, 1, 5, 9]])

In [98]:
x2[2, 1]

1

In [99]:
x2[2, 0]

8

In [100]:
x2[2, -1]

9

In [101]:
x2[0, 0] = 12
x2

array([[12,  6,  8,  8],
       [ 1,  6,  7,  7],
       [ 8,  1,  5,  9]])

In [104]:
print x1
print x1.dtype

[5 0 3 3 7 9 3 5 2 4]
int32


In [107]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9, 3, 5, 2, 4])

In [122]:
arr1 = np.array([1,2,5,3,5])
arr2d = np.array([[1,2],[2,3,5],[4,5]])
print arr1
print arr2d

[1 2 5 3 5]
[[1, 2] [2, 3, 5] [4, 5]]


In [111]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [113]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [114]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [115]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [116]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [117]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [118]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

In [126]:
x2

array([[12,  6,  8,  8],
       [ 1,  6,  7,  7],
       [ 8,  1,  5,  9]])

In [131]:
x2[1:,1:3]

array([[6, 7],
       [1, 5]])

In [127]:
x2[:2, :3]

array([[12,  6,  8],
       [ 1,  6,  7]])

In [129]:
x2[2, 2:]

array([5, 9])

In [130]:
x2[:2,:3]

array([[12,  6,  8],
       [ 1,  6,  7]])

In [26]:
x2[:2, :3]  # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [132]:
x2[:3, ::2]  # all rows, every other column

array([[12,  8],
       [ 1,  7],
       [ 8,  5]])

In [133]:
x2[::-1, ::-1]

array([[ 9,  5,  1,  8],
       [ 7,  7,  6,  1],
       [ 8,  8,  6, 12]])

In [134]:
print x2[:, 0]  # first column of x2

[12  1  8]


In [135]:
print x2[0, :]  # first row of x2

[12  6  8  8]


In [136]:
print x2[0]  # equivalent to x2[0, :]

[12  6  8  8]


In [137]:
print x2

[[12  6  8  8]
 [ 1  6  7  7]
 [ 8  1  5  9]]


In [138]:
x2_sub = x2[:2, :2]
print x2_sub

[[12  6]
 [ 1  6]]


In [143]:
x2 = np.arange(12).reshape(3,4)
x2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [145]:
x2[1:,2:] = -1

In [146]:
x2

array([[ 0,  1,  2,  3],
       [ 4,  5, -1, -1],
       [ 8,  9, -1, -1]])

In [147]:
x2_sub = x2[:2,:2]
x2_sub

array([[0, 1],
       [4, 5]])

In [148]:
x2_sub[0,0] = 99

In [149]:
x2_sub

array([[99,  1],
       [ 4,  5]])

In [150]:
x2

array([[99,  1,  2,  3],
       [ 4,  5, -1, -1],
       [ 8,  9, -1, -1]])

In [139]:
x2_sub[0, 0] = 99
print x2_sub

[[99  6]
 [ 1  6]]


In [140]:
print x2

[[99  6  8  8]
 [ 1  6  7  7]
 [ 8  1  5  9]]


In [152]:
x2_sub_copy = x2[:2, :2].copy()
print x2_sub_copy 

[[99  1]
 [ 4  5]]


In [153]:
x2_sub_copy[0, 0] = 42
print x2_sub_copy 

[[42  1]
 [ 4  5]]


In [154]:
print x2 

[[99  1  2  3]
 [ 4  5 -1 -1]
 [ 8  9 -1 -1]]


In [155]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [156]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [157]:
np.vstack([grid,x])

array([[9, 8, 7],
       [6, 5, 4],
       [1, 2, 3]])

In [41]:
# horizontally stack the arrays
np.hstack([grid[0,:], x])

array([9, 8, 7, 1, 2, 3])

In [170]:
def reverse(string):
    out = ''
    i=1
    length = len(string)
    while length > 0:
        out = out + string[length-i]
        length = length-1
    return out

print reverse("home")

emoh


In [168]:
'home'[3]

'e'