# Computation on NumPy Arrays: Universal Functions

In [1]:
import numpy as np

In [6]:
x = np.arange(5)

In [7]:
y = np.arange(1, 6)

In [8]:
x + y

array([1, 3, 5, 7, 9])

In [11]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [9]:
x*y

array([ 0,  2,  6, 12, 20])

In [14]:
x = np.arange(9).reshape((3, 3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [16]:
x ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [19]:
x2 = [1,2,3,4,5]
[x + 5 for x in x2]

[6, 7, 8, 9, 10]

In [20]:
x = np.arange(4)
print x
print "x     =", x
print "x + 5 =", x + 5
print "x - 5 =", x - 5
print "x * 2 =", x * 2
print "x / 2 =", x / 2.0
print "x // 2 =", x // 2  # floor division

[0 1 2 3]
x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [ 0.   0.5  1.   1.5]
x // 2 = [0 0 1 1]


In [8]:
print "-x     = ", -x
print "x ** 2 = ", x ** 2
print "x % 2  = ", x % 2

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [21]:
-((0.5*x + 1) ** 2)

array([-1.  , -2.25, -4.  , -6.25])

## Universal Functions

In [22]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [23]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [24]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [25]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([ 5.,  5.,  2.,  1.])

In [28]:
np.pi

3.141592653589793

In [30]:
theta = np.linspace(0, np.pi, 6)

In [31]:
print "theta      = ", theta
print "sin(theta) = ", np.sin(theta)
print "cos(theta) = ", np.cos(theta)
print "tan(theta) = ", np.tan(theta)

theta      =  [ 0.          0.62831853  1.25663706  1.88495559  2.51327412  3.14159265]
sin(theta) =  [  0.00000000e+00   5.87785252e-01   9.51056516e-01   9.51056516e-01
   5.87785252e-01   1.22464680e-16]
cos(theta) =  [ 1.          0.80901699  0.30901699 -0.30901699 -0.80901699 -1.        ]
tan(theta) =  [  0.00000000e+00   7.26542528e-01   3.07768354e+00  -3.07768354e+00
  -7.26542528e-01  -1.22464680e-16]


In [32]:
x = np.linspace(0,5,5)
print "x     =", x 
print "e^x   =", np.exp(x) 
print "2^x   =", np.exp2(x)
print "3^x   =", np.power(3, x)
print "x^3   =", np.power(x, 3)

x     = [ 0.    1.25  2.5   3.75  5.  ]
e^x   = [   1.            3.49034296   12.18249396   42.521082    148.4131591 ]
2^x   = [  1.           2.37841423   5.65685425  13.45434264  32.        ]
3^x   = [   1.            3.94822204   15.58845727   61.54669054  243.        ]
x^3   = [   0.          1.953125   15.625      52.734375  125.      ]


In [33]:
print "x        =", x
print "ln(x)    =", np.log(x)
print "log2(x)  =", np.log2(x)
print "log10(x) =", np.log10(x)

x        = [ 0.    1.25  2.5   3.75  5.  ]
ln(x)    = [       -inf  0.22314355  0.91629073  1.32175584  1.60943791]
log2(x)  = [       -inf  0.32192809  1.32192809  1.9068906   2.32192809]
log10(x) = [       -inf  0.09691001  0.39794001  0.57403127  0.69897   ]


C:\Users\Alvaro\AppData\Local\Dato\Dato Launcher\lib\site-packages\ipykernel\__main__.py:2: RuntimeWarning: divide by zero encountered in log
  from ipykernel import kernelapp as app
C:\Users\Alvaro\AppData\Local\Dato\Dato Launcher\lib\site-packages\ipykernel\__main__.py:3: RuntimeWarning: divide by zero encountered in log2
  app.launch_new_instance()
C:\Users\Alvaro\AppData\Local\Dato\Dato Launcher\lib\site-packages\ipykernel\__main__.py:4: RuntimeWarning: divide by zero encountered in log10


In [13]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [14]:
np.multiply.reduce(x)

120

In [15]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [16]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

In [30]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])