# Numpy Exercises

In [1]:
import numpy as np

#### Print the numpy version

In [5]:
print np.__version__

1.10.4


#### Create the following vectors

In [6]:
# A vector of zeros of size 10 but the fifth value equal to 1
vec1 = np.zeros(10)
vec1[4] = 1
print vec1

# A vector with values ranging from 1 to 50
vec2 = np.arange(1,51)
print vec2

# A vector with the integer multiples of 5 less than 100
vec3 = np.arange(0,100,5)
print vec3

# Reverse the vector reciently created (first element becomes last)
vec3[::-1]

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


array([95, 90, 85, 80, 75, 70, 65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15,
       10,  5,  0])

#### Create a 3x3 matrix with values ranging from 1 to 9

In [9]:
x = np.arange(1,10)
x.resize(3,3) # Modifies the array in-place
x.reshape(3,3) # returns a copy with modified dimensions

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Find indices of non-zero elements from ``[1,2,0,0,4,0]``

In [10]:
my_array = np.array([1,2,0,0,4,0])
np.nonzero(my_array)

(array([0, 1, 4], dtype=int64),)

In [11]:
my_array.dtype

dtype('int32')

#### Create a 10x10 array with random values and find the minimum and maximum values

In [12]:
M = np.random.randint(0,100, size=(10,10))
M

array([[46, 72, 50,  0, 36, 40, 33, 89, 62,  3],
       [47, 82, 61, 12, 37, 25, 97,  9, 24, 48],
       [55, 11, 44, 48,  8, 87, 51, 60, 65, 10],
       [ 7, 34, 19, 67,  1, 84, 31, 96, 67,  8],
       [11, 18,  4, 60, 24,  8, 19,  7, 73, 82],
       [94,  9, 39, 82, 50, 45,  2, 70, 52, 34],
       [95, 55, 31, 58, 24, 73, 32, 58, 23, 42],
       [ 6, 12, 54,  7, 74, 38,  7, 51, 60, 55],
       [93, 16, 50, 33, 23, 25, 69, 45, 96, 14],
       [91, 80, 67, 78, 36, 21, 15, 98, 90,  0]])

In [15]:
print M.min(axis=1)
print M.max(axis=0)

[ 0  9  8  1  4  2 23  6 14  0]
[95 82 67 82 74 87 97 98 96 82]


#### Create a random vector of size 30 and find the mean and the standard deviation

In [16]:
x = np.random.random(30)
print x.mean()
print x.std()

0.503955464615
0.313753244374


#### Create random vector of size 10 and replace the maximum value by 0

In [19]:
x = np.random.random(10)

In [21]:
x[x.argmax()] = 10
x

array([  4.32164753e-01,   5.54877544e-01,   1.00000000e+01,
         4.82966992e-01,   3.73299500e-01,   4.81296865e-02,
         1.37820273e-01,   4.63702792e-02,   6.40694438e-01,
         5.89950578e-03])

#### Create two arrays of size 10 with random integers between 1 and 20. Find common numbers between two arrays.

#### Create a 3 x 5 matrix of integers from 0 to 9, find the sums of the rows, the columns and the whole matrix

#### Calculate the values of the function $f(x) = x^2 + 3x - 6$ for 100 numbers in from -2 to 2

#### Implement the following algorithm in a function to detect outliers:
1. Calculate the first and third quartiles $Q_1, Q_3$ of a vector.
1. Calculate the inter-quartile range (IQR) of a vector.
2. Categorize as outliers any value outside the intervar $[Q_1 - 1.5IQR, Q_3 + 1.5IQR]$

#### Using the same algorithm as before, implement a function that replaces all the outliers with the appropiate endpoint of the given interval (for small outliers use the left endpoint and for large outliers the right one)

#### Create a 2d array of shape (10,10) with 1 on the border and 0 inside

#### Using the standard normal distribution create a random vector of size 100. Find the closest value to 1

#### Repeate the same excersise as above but this time create a 100 x 10 matrix. Find the closest value to 1 in every column.

#### Create a matrix 20 x 5 with random normal values with mean=100. Subtract the mean of each column of the matrix

#### Create an array of 100 integers from 0 to 9. Find the most and the least frequent values in the array.

#### Simulate tossing a fair coin 20 times, count the number of "heads".

#### As in the last exercise, simulate tossing a fair coin 20 times, do the same simulation 1,000 times. Count the number of "heads" for each simulation (save them in an array counts). Report and give an interpretation of the descriptive statistics of counts. Print the distribution of counts