# Comparisons, Masks, and Boolean Logic

In [3]:
import numpy as np

In [5]:
x = np.array([1, 2, 3, 4, 5])

In [6]:
x < 3  # less than

array([ True,  True, False, False, False], dtype=bool)

In [8]:
x > 3  # greater than

array([False, False, False,  True,  True], dtype=bool)

In [9]:
x <= 3  # less than or equal

array([ True,  True,  True, False, False], dtype=bool)

In [10]:
x >= 3  # greater than or equal

array([False, False,  True,  True,  True], dtype=bool)

In [11]:
x != 3  # not equal

array([ True,  True, False,  True,  True], dtype=bool)

In [12]:
x == 3  # equal

array([False, False,  True, False, False], dtype=bool)

In [14]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False], dtype=bool)

In [15]:
x = np.random.randint(0,10, size=(3, 4))
x

array([[0, 8, 0, 5],
       [5, 9, 4, 8],
       [9, 9, 8, 7]])

In [16]:
x < 6

array([[ True, False,  True,  True],
       [ True, False,  True, False],
       [False, False, False, False]], dtype=bool)

In [17]:
# how many values less than six?
np.count_nonzero(x < 6)

5

In [18]:
np.sum(x < 6)

5

In [20]:
# how many values less than six in each row?
np.sum(x < 6, axis=0)

array([2, 0, 2, 1])

In [21]:
# are there any values greater than eight?
np.any(x > 8)

True

In [22]:
# are there any values less than zero?
np.any(x < 0)

False

In [23]:
# are all values less than ten?
np.all(x < 10)

True

In [24]:
# are all values less than 8?
np.all(x < 8)

False

In [10]:
# are all values equal to six?
np.all(x == 6)

False

In [11]:
# are all values in each row less than four?
np.all(x < 4, axis=1)

array([False, False, False], dtype=bool)

In [12]:
x

array([[3, 5, 0, 3],
       [5, 5, 1, 2],
       [8, 3, 9, 9]])

In [13]:
x < 5

array([[ True, False,  True,  True],
       [False, False,  True,  True],
       [False,  True, False, False]], dtype=bool)

### Boolean mask

In [25]:
x = np.random.randint(0,10,15)

In [26]:
x

array([7, 5, 1, 8, 2, 1, 9, 0, 4, 1, 0, 9, 2, 1, 0])

In [27]:
x > 8

array([False, False, False, False, False, False,  True, False, False,
       False, False,  True, False, False, False], dtype=bool)

In [28]:
x[x > 8]

array([9, 9])

In [29]:
x[x > 1]

array([7, 5, 8, 2, 9, 4, 9, 2])

In [30]:
x[(x >= 2) & (x <= 6)]

array([5, 2, 4, 2])

In [32]:
x.argmin()

7

In [34]:
x.shape # equivalent to len()

(15L,)